language: node_js
os: linux
dist: xenial
install: yarn install --frozen-lockfile --ignore-engines
before_script: yarn build
env:
  - mode=dev
jobs:
  allow_failures:
  - name: Node 10
  - name: Node 11
  - name: Latest Node - OSX
  include:
  - name: Node 10
    node_js: 10
  - name: Node 11
    node_js: 11
  - name: Node 12
    node_js: 12
  - name: Node 13
    node_js: 13
  - name: Node 14
    node_js: 14
  - name: Node 15
    node_js: 15
  - name: Node 16
    node_js: 16
  - name: Node 17
    node_js: 17
#  - name: Latest Node - Windows
#    node_js: node
#    os: windows
  - name: Latest Node - OSX
    node_js: node
    os: osx
  - name: Latest Node - Linux
    node_js: node
    os: linux
    env:
      - mode=dev
    after_success: yarn run coverage
